### PR TITLE
Updated gemfile - upgrade to rails 4.2.2

### PR DESCRIPTION
**Pull request by jacemonje**

### CODE REVIEW

**Comment by NuckChorris** [comment]
We can't just update to 4.2, there's work which needs doing. See https://www.pivotaltracker.com/story/show/89862350

**Comment by NuckChorris** [comment]
Additionally this would also need Gemfile.lock to be updated with `bundle update rails`

**Comment by jacemonje** [comment]
I see. I didn't see that pivotal tracker ticket, sorry!

**Comment by DNA** [comment]
For what I saw, we need to update the `devise` gem, add maybe add the `responder` gem, since devise need it in some cases (the docs says so, but they don't add it as a dependence). The `non-stupid-digest-assets` gem also seems to be fine.

But I'm pretty sure that all this changes will throw a lot of errors on the tests :P

**Comment by NuckChorris** [comment]
Honestly I don't think it'll break too many tests once the libraries are updated and tweaked.

**Pull request closed without merging**
