### PR TITLE
resolve rubocop offenses in full_manga_controller.rb

### PR DESCRIPTION
**Pull request by Eschon**
Another big one :p

### CODE REVIEW

**Comment by JoshFabian** [comment]
Hey Eschon, are you in our Slack Dev Chat yet?

**Comment by Eschon** [comment]
Nope

**Comment by JoshFabian** [comment]
What email should I send your invite to? :)

**Comment by Eschon** [comment]
Can you see the one I'm using on github?
I don't want to post it here, because I somehow managed to keep it spam free :p

**Comment by JoshFabian** [comment]
I cannot, just shoot me an email contact@joshfabian.com

**Comment by Eschon** [comment]
Done

**Pull request merged**
