### PR TITLE
Fixed css issue with when no notifications

### PR DESCRIPTION
**Pull request by v4lproik**
Before

screen shot 2015-04-22 at 16 54 59

After

screen shot 2015-04-22 at 17 11 34

### CODE REVIEW

**Comment by Kenshii** [comment]
border-bottom should be used instead of <hr>, to conform with how it's done for notifications.
There's also a large gap above 'View All Notifications' in the screenshot.

I personally prefer something like this.
```.no-notifications {
  text-align: center;
  padding-top: 10px;
  padding-bottom: 10px;
  border-bottom: 1px solid #eee;
}```

On a similar note:
View All Notifications isn't centered properly by HB currently.
I think the class should be changed from "notification view-all" to simply "view-all"

With the notification class omitted, it'd look like this:
![image](https://cloud.githubusercontent.com/assets/290316/7287116/ba8a7752-e949-11e4-8465-2d6bb243ae81.png)

**Comment by vevix** [comment]
:+1: on @Kenshii suggestions

**Comment by v4lproik** [comment]
Done, thx @Kenshii.

**Comment by vevix** [comment]
Is there a reason why you closed this?

**Comment by NuckChorris** [comment]
You don't need to close and reopen a PR to make changes. When you push to the branch it will update the PR

**Comment by v4lproik** [comment]
Sorry, I closed it after I had updated my branch with @Kenshii notes.

Did I make a mistake ?

**Comment by vevix** [comment]
You should only close Pull Requests when you don't want them to be merged anymore :D, thanks for re-opening.

**Comment by vevix** [comment]
Thanks @v4lproik :+1:

**Comment by v4lproik** [comment]
I am sorry, thought it was the issue topic. Wake up coffee first and then PR. Thanks guys :+1:

**Comment by vevix** [comment]
Yeah, previously GitHub had it so when you created a PR it also created an issue, however, they are now separated! :+1:

**Pull request merged**
