### PR TITLE
Collapse NSFW stories by default

### PR DESCRIPTION
**Pull request by fractalemagic**
It's not great, but it does the job for now.

Example

### CODE REVIEW

**Comment by NuckChorris** [comment]
Few problems: first of all, this collapses all posts, doesn't it?

Second, we need to also collapse comment images.

We should probably use the same hooks we us for spoilers.

**Comment by fractalemagic** [comment]
Oh right, I forgot about comments ¯\\_(ツ)_/¯ And no it won't collapse all posts, only adult ones.

`collapsed: Ember.computed.equal('model.adult', true)`

**Comment by vevix** [comment]
Do you plan to update this to handle comments too? Otherwise, I'm a fan :+1:

/cc @Josh

**Comment by JoshFabian** [comment]
This looks good to me! We can update it later to be a little sexier but I think this is a great start that gets the job done. Supporting comments would be ideal but something is better than nothing.

**Comment by fractalemagic** [comment]
Comments are hidden :smiley: 

Hidden Comments

**Comment by JoshFabian** [comment]
You rock

**Pull request merged**
