### PR TITLE
fix titles for english preference

### PR DESCRIPTION
**Pull request by vevix**
REF: #623 

Anything else needed? We should get this pushed ASAP /cc @DNA

### CODE REVIEW

**Comment by vevix** [comment]
Also fixed what seems to be a bug reported here: https://forums.hummingbird.me/t/canonical-titles-only-showing-as-romanized/26846

Our title code is pretty bad, I think @NuckChorris was working on a change for it :(.

**Comment by NuckChorris** [comment]
I was hoping to refactor it into a separate table but thats more of a long term endeavor and between my feed refactor and oauth2 I've already got enough patches to stage.

For now I think renaming them english_title and romaji_title would help greatly.

**Comment by DNA** [comment]
This should resolve all the present bugs until do a better refactor :)

**Comment by DNA** [comment]
Maybe add some tests to check if we are not presenting empty string as valid ones? It'll help in the next refactor too

**Pull request merged**
