### PR TITLE
Fixed issue #498 - Anime quotes don't wrap long words

### PR DESCRIPTION
**Pull request by v4lproik**

### CODE REVIEW

**Comment by v4lproik** [comment]
With the float property, the word-wrap property is not taken into account.

screen shot 2015-04-22 at 13 46 34

**Comment by Epictek** [comment]
the float line should probably be removed then?

**Comment by vevix** [comment]
Can you rebase the commits into one? Will merge after that

Thanks! :+1:

**Comment by vevix** [comment]
If you're having trouble squashing, check out https://help.github.com/articles/about-git-rebase/#rebasing-commits-against-a-point-in-time

**Comment by vevix** [comment]
:+1:

**Pull request merged**
