### PR TITLE
Add paranoia gem

### PR DESCRIPTION
**Pull request by NuckChorris**
This gem allows us to _fake_ deleting things.  Meaning, it's not actually deleted, it just pretends to be.  So we have an audit trail.

For example, if a user is being harassed and they delete the posts, we'd probably still want to see the posts.  Right now, the only way to view them is to go into rails_admin (I assume it'll work in there, not sure though actually) but in future I'd like to serialize `deleted_at` and display deleted posts (with visual distinction obviously) to administrators

### CODE REVIEW

**Comment by vevix** [comment]
Are we going to need to add anything to our queries to not serialize deleted posts?

**Comment by NuckChorris** [comment]
Nope, this gem overrides `default_scope` on the model.  I even checked that `find` queries will return nothing

**Comment by vevix** [comment]
Okay awesome :+1:

**Comment by NuckChorris** [comment]
Rebased, ready for merge?

**Comment by vevix** [comment]
:+1:

**Pull request merged**
