### PR TITLE
Update ember-cli from 0.1.3 to 0.1.7

### PR DESCRIPTION
**Pull request by cybrox**
According to http://www.ember-cli.com/#upgrading

### CODE REVIEW

**Comment by NuckChorris** [comment]
I don't see much which could blow things up, outside of the beta bump on `ember-data` and the patch bumps on various Rails gems.  :+1: from me.

**Comment by vikhyat** [comment]
Maybe also upgrade the ember-cli-rails gem and ember adding while we're doing this?

**Comment by cybrox** [comment]
@vikhyat `ember-cli-rails` gem has been updated as well in the second commit.
Ember, Ember data and the `ember-cli-rails-addon` have been updated during the ember-cli update.

**Comment by vikhyat** [comment]
awesome

**Pull request merged**
