### PR TITLE
Force rspec to run on test environment

### PR DESCRIPTION
**Pull request by DNA**
As we talked yesterday on Slack, we need to enforce Rspec to run on the test development :)

### CODE REVIEW

**Comment by vevix** [comment]
I think this will still happen under `bin/guard` since it executes `server/bin/rspec` under development env.

**Comment by NuckChorris** [comment]
Yeah this should probably also happen to `bin/guard`

**Comment by DNA** [comment]
I've tested both and they are working fine now. And since we can just pass `bin/rake RAILS_ENV=test task` when needed, I don't think we need to change other scripts :)

**Comment by NuckChorris** [comment]
LGTM!

**Comment by DNA** [comment]
Can I haz merge? :P

**Pull request merged**
