### PR TITLE
Publish manga favs and nsfw posts

### PR DESCRIPTION
**Pull request by cybrox**
- Publish manga favorites and nsfw posts for all users
- Hide Manga box for other users if it's empty (prevent ugly double error message)

### CODE REVIEW

**Comment by NuckChorris** [comment]
Outside of the showSelf, this is a +1 from me, let's get that shit to the masses!

**Comment by cybrox** [comment]
I guess using `showContainer` would be a solution?

**Comment by NuckChorris** [comment]
Would `showMangaFavorites` be better?  It's kind of redundant due to context but it certainly gets the point across

**Comment by cybrox** [comment]
Yeah, I guess that'd make sense.

**Comment by NuckChorris** [comment]
Once the build light stops eyeing us judgementally, lgtm

**Pull request merged**
