### PR TITLE
Fix avatar shrinking before break into mobile layout

### PR DESCRIPTION
**Pull request by Wopian**
Just getting rid of remnants from the old user page design.

Before:

After:

### CODE REVIEW

**Comment by JoshFabian** [comment]
I think some shrinkage is still needed so that the avatar isn't so tight up against the sub-nav.

**Comment by Wopian** [comment]
:+1: reverted to 109px earlier, which makes the avatar in-line with the bottom of the bio text.

**Comment by Wopian** [comment]
Updated `After` image to reflect changes @JoshFabian

**Comment by JoshFabian** [comment]
LGTM! +1

**Pull request merged**
