### PR TITLE
use bitcoin for non-recurring plans only

### PR DESCRIPTION
**Pull request by vevix**
:arrow_up: :arrow_down: :moneybag:

### CODE REVIEW

**Comment by NuckChorris** [comment]
It's 3AM so I probably should not review code and just go to bed but

:dango: :shipit: :pizza: lgtm

**Comment by vevix** [comment]
trust me, its perfect :trollface:

**Comment by NuckChorris** [comment]
There's no swear words being logged to the console, I think that makes it more solid than some of my PRs

**Comment by vevix** [comment]
Travis is :trollface: `running for 23m 19s`

**Pull request merged**
