### PR TITLE
Remove margin-top on onboarding pages to reveal false header again

### PR DESCRIPTION
**Pull request by JoshFabian**

### CODE REVIEW

**Comment by NuckChorris** [comment]
Are you sure you pushed the right changes?  Cause that commit removes the entire onboarding header, not the margin-top

**Comment by NuckChorris** [comment]
In all fairness, you probably *did* fix the issue.

Just with a bit of collateral damage.

**Comment by JoshFabian** [comment]
Yeah, I was uh, having issues with ember not displaying my updates so I tested just removing everything to see if it was caching or what. I forgot to revert before pushing. I'm dumb.

**Pull request closed without merging**
