### PR TITLE
Use MessageFormatter to format the user and group about text

### PR DESCRIPTION
**Pull request by NuckChorris**
Exactly as the title says, this uses the `MessageFormatter` service to expose formatting capabilities in the about section.  I haven't really tested it, because I'm just doing this between things today.  Merge with caution.

This should do [Convert newlines in "about" section to &lt;br&gt; tags](https://www.pivotaltracker.com/story/show/88584772)

### CODE REVIEW

**Comment by vevix** [comment]
Looks good :+1: Is there any worry about people putting YouTube/Gfy embeds in their about?

**Comment by NuckChorris** [comment]
I for one encourage people to put more gifs and gfycats in their about box :D

**Comment by JoshFabian** [comment]
Will this also use onebox when that is merged in?

**Comment by NuckChorris** [comment]
Yep. This also provides spoilers (which probably won't work actually, we should fix that) and if we add markdown here it also adds it to feeds.

**Pull request merged**
