### PR TITLE
Removed deadman from app list

### PR DESCRIPTION
**Pull request by Mikunj**

### CODE REVIEW

**Comment by dulleh** [comment]
https://forums.hummingbird.me/t/ios-deadman/20315/176  ...and it's not like it's stopped working for those that already have it.

**Comment by Mikunj** [comment]
I can always revert changes later when i redeem. Just want to remove from the app page so that new people don't try and click the link and get nothing

**Comment by dulleh** [comment]
Ah! Sorry, didn't recognise you ;)

**Comment by NuckChorris** [comment]
:+1: For now this is wise, if sad.

**Pull request merged**
