### PR TITLE
Favorite refactoring, final tweaks

### PR DESCRIPTION
**Pull request by cybrox**
Fixes all reported bugs, optimizes requests and adds a loading state

### CODE REVIEW

**Comment by NuckChorris** [comment]
You should probably put more of this in the component than you are but for now it's a +1 from me

**Comment by cybrox** [comment]
Well, I mainly focused the structures on just putting reusable things into components - or things we actually use elsewhere - so a lot of it is left in the user.index controller as before, yeah.
We might need to clarify, if we want to strictly follow the *component-ize everything* approcha in the future.

**Comment by NuckChorris** [comment]
I think "componentize" should at least happen when you have nearly identical code between manga and anime :stuck_out_tongue:

**Comment by cybrox** [comment]
Guess you're right on that one.
I'll just merge this to deploy the fixes for now and put the small *refactor thigns into the component* on the to-do list.

**Comment by NuckChorris** [comment]
:+1:

**Pull request merged**
