### PR TITLE
Rack::Attack for story creation

### PR DESCRIPTION
**Pull request by NuckChorris**
Limit users to 30 posts per 30 minutes.  I feel this is unlikely to be hit by most users, but low enough to block the worst of spammers (ie jvcs22)

### CODE REVIEW

**Comment by vevix** [comment]
:+1:

**Comment by DNA** [comment]
:+1 a limit of a post per minute seems fine :)

**Comment by DNA** [comment]
:+1: a limit of a post per minute seems fine :smile:

**Comment by NuckChorris** [comment]
Technically it's not one per minute, it's 30 per 30 — this allows them to do 30 posts in one minute and then forces them to shut up for 29 minutes.

Debating whether this is better or just a 1 per 20 seconds.  This 30-per-30m seems like it might cause more collateral damage than the 1 per 20s

**Comment by DNA** [comment]
Yeah, I understood that, my english proficiency failed to explain that xD

**Pull request merged**
